server:
  port: 8080

spring:
  application:
    name: smart-clinic-backend

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      

  datasource:
    url: jdbc:h2:mem:smartclinic;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    defer-datasource-initialization: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/smartclinic

app:
  security:
    jwt-secret: replace-with-a-strong-secret-for-local-dev-only
    jwt-expiration-ms: 86400000